#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Jul 14 11:33:28 CEST 2018
# SW Build 2188600 on Wed Apr  4 18:39:19 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto be19da0f367b43c3b1274050c944e8d7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L util_vector_logic_v2_0_1 -L xlconstant_v1_1_4 -L xlconcat_v2_1_1 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot design_1_wrapper_tb_behav xil_defaultlib.design_1_wrapper_tb xil_defaultlib.glbl -log elaborate.log
