webtalk_init -webtalk_dir /home/wojak/Vivado_Projects/HDMI_Transmitter/HDMI_Transmitter.sim/sim_2/behav/xsim/xsim.dir/design_1_wrapper_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul 12 13:18:39 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "74ffef59-44da-4471-807f-157680d33ca5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "be19da0f367b43c3b1274050c944e8d7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3274.832 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.46_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125080_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2221134518 -regid "" -xml /home/wojak/Vivado_Projects/HDMI_Transmitter/HDMI_Transmitter.sim/sim_2/behav/xsim/xsim.dir/design_1_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/wojak/Vivado_Projects/HDMI_Transmitter/HDMI_Transmitter.sim/sim_2/behav/xsim/xsim.dir/design_1_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/wojak/Vivado_Projects/HDMI_Transmitter/HDMI_Transmitter.sim/sim_2/behav/xsim/xsim.dir/design_1_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
